version: 1.0.{build}
image: Visual Studio 2019
clone_folder: C:\a\udp-discovery-cpp
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  APPVEYOR_RDP_PASSWORD: '*Bmor34nC+(sp44'
  global:
## Qt: https://www.appveyor.com/docs/installed-software#qt
#    QTDIR: C:\Qt\5.10.1\mingw53_32
    MSYS2_ARCH: i686
    TARGET: i686_32-pc-msys
    MINGW_PREFIX: C:\msys64\mingw32
build_script:
- cmd: >-
    C:\msys64\autorebase.bat

    cd C:\a\udp-discovery-cpp

    mkdir build

    cd build

    cmake -DBUILD_EXAMPLE=ON -DBUILD_TOOL=ON ..

    cmake --build ./
on_failure:
- ps: >-
    #To get RDP running after compiling

    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
- ps: >-
    #To get RDP running after compiling

    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
